export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const DISPLAY_MOVIES = 'DISPLAY_MOVIES';
export const DISPLAY_MOVIE = 'DISPLAY_MOVIE';
export const LOADING = 'LOADING';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const ADD_TO_WATCHED = 'ADD_TO_WATCHED';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const REMOVE_FROM_WATCHED= 'REMOVE_FROM_WATCHED';




